taks_3/config/routes.rb
Taks3::Application.routes.draw do
  resources :persons
  root :to => "houses#index"
  resources :houses

end

taks_3/app/models/house.rb
class House < ActiveRecord::Base
end

taks_3/app/models/person.rb
class Person < ActiveRecord::Base
end

taks_3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

taks_3/app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def new
    @house = House.new
  end
  def create
    @house = House.new(params_house)
    if @house.save
      flash[:notice] ="Data Saved"
      redirect_to action: 'index'
    else
      flash[:error]= "data not valid"
      render 'new'
    end
  end

  def edit
    @house = House.find_by_id(params[:id])
  end
  def update
    @house = House.find_by_id(params[:id])
    if @house.update(params_house)
      flash[:notice] = "Data updated"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

  def destroy
    @house = House.find_by_id(params[:id])
    if @house.destroy
      flash[:notice] = "Data Deleted"
      redirect_to action: 'index'
    else
      flash[:error] = "fails to delete data"
      redirect_to action: 'index'
    end
  end

private
  def params_house
    params.require(:house).permit(:houseno,:tipe,:address)
  end
end

taks_3/app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @persons = Person.all
  end

  def new
    @person = Person.new
  end
  def create
    @person = Person.new(params_person)
    if @person.save
      flash[:notice] = "Data saved"
      redirect_to action: 'index'
    else
      flash[:error] ="data not valid"
      render 'new'
    end
  end

  def edit
    @person = Person.find_by_id(params[:id])
  end
  def update
    @person = Person.find_by_id(params[:id])
    if @person.update(params_person)
       flash[:notice] = "Data updated"
      redirect_to action: 'index'
    else
      flash[:error] ="data not valid"
      render 'edit'
    end
  end

  def destroy
    @person = Person.find_by_id(params[:id])
    if @person.destroy
      flash[:notice] = "Data deleted"
      redirect_to action: 'index'
    else
      flash[:error] ="fails to delete data"
      redirect_to action: 'index'
    end
  end

private
  def params_person
    params.require(:person).permit(:name,:noktp,:birthdate,:houseid)
  end
end

taks_3/app/helpers/application_helper.rb
module ApplicationHelper
end

taks_3/app/views/houses/edit.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Residents</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/houses/">Rumah</a></li>
      <li><a href="/persons/">Orang</a></li>
    </ul>
  </div>
</div>
<h1>Houses#edit</h1>
<%= form_for @house, html:{class:"form-horizontal"} do |f| %>
<fieldset>
<legend>Form House</legend>
<div class="form-group">
  <%= f.label :houseno, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :houseno, class:"form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :tipe,class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :tipe, class:"form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :address,class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :address, class:"form-control" %>
  </div>
</div>
<br/>
<%= f.submit :submit, class:"btn btn-primary" %>
</fieldset>
<% end %>

taks_3/app/views/houses/index.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Residents</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/houses/">Rumah</a></li>
      <li><a href="/persons/">Orang</a></li>
    </ul>
  </div>
</div>

<h1>Houses#index</h1>
<table class="table table-bordered">
<thead>
  <tr class="info">
    <td>No</td>
    <td>Tipe</td>
    <td>Alamat</td>
    <td>Pilihan</td>
  </tr>
</thead>
<% @houses.each do |house| %>
  <tr class=warning>
    <td><%= house.houseno %></td>
    <td><%= house.tipe %></td>
    <td><%= house.address %></td>
    <td><%= link_to 'Edit', edit_house_path(house.id) %> | <%= link_to 'Delete', house_path(house.id), method: "DELETE", data:{confirm: 'Delete this data?'} %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Create New', new_house_path %>

taks_3/app/views/houses/new.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Residents</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/houses/">Rumah</a></li>
      <li><a href="/persons/">Orang</a></li>
    </ul>
  </div>
</div>

<h1>House#new</h1>
<%= form_for @house, html:{class:"form-horizontal"} do |f| %>
<fieldset>
<legend>Form House</legend>
<div class="form-group">
  <%= f.label :houseno, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :houseno, class:"form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :tipe,class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :tipe, class:"form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :address,class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :address, class:"form-control" %>
  </div>
</div>
<br/>
<%= f.submit :submit, class:"btn btn-primary" %>
</fieldset>
<% end %>

taks_3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taks3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

taks_3/app/views/persons/edit.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Residents</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/houses/">Rumah</a></li>
      <li><a href="/persons/">Orang</a></li>
    </ul>
  </div>
</div>

<h1>Persons#edit</h1>
<%= form_for @person, html:{class:"form-horizontal"} do |f| %>
<fieldset>
<legend>Form Person</legend>
<div class="form-group">
  <%= f.label :houseid, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :houseid, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :name, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :noktp, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :noktp, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :birthdate, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :birthdate, class: "form-control" %>
  </div>
</div>
<br/>
<%= f.submit :submit, class:"btn btn-primary" %>
</fieldset>
<% end %>

taks_3/app/views/persons/index.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Residents</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/houses/">Rumah</a></li>
      <li><a href="/persons/">Orang</a></li>
    </ul>
  </div>
</div>

<h1>Persons#index</h1>
<table class="table table-bordered">
<thead>
  <tr class="info">
    <td>ID Rumah</td>
    <td>Nama</td>
    <td>no. KTP</td>
    <td>Tanggal Lahir</td>
    <td>Pilihan</td>
  </tr>
</thead>
<% @persons.each do |person| %>
  <tr class="warning">
    <td><%= person.houseid %></td>
    <td><%= person.name %></td>
    <td><%= person.noktp %></td>
    <td><%= person.birthdate %></td>
    <td><%= link_to 'Edit', edit_person_path(person.id) %>  |  <%= link_to 'Delete', person_path(person.id), method: "DELETE", data:{confirm: 'Delete this data ?'} %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Create New', new_person_path %>

taks_3/app/views/persons/new.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Residents</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/houses/">Rumah</a></li>
      <li><a href="/persons/">Orang</a></li>
    </ul>
  </div>
</div>

<h1>Persons#edit</h1>
<%= form_for @person, :url => {action: "create" }, html:{class:"form-horizontal"} do |f| %>
<fieldset>
<legend>Form Person</legend>
<div class="form-group">
  <%= f.label :houseid, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :houseid, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :name, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :noktp, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :noktp, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-group">
  <%= f.label :birthdate, class: "col-lg-1 control-label" %>
  <div class="col-lg-4">
    <%= f.text_field :birthdate, class: "form-control" %>
  </div>
</div>
<br/>
<%= f.submit :submit, class:"btn btn-primary" %>
</fieldset>
<% end %>